In [1]:
import pandas as pd
#import requests
import yfinance as yf
#from pandas.io.json import json_normalize
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.dates as mdates

In [13]:
dat = yf.Ticker("MSFT")
dat.history(period='1mo')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-01-14 00:00:00-05:00,417.809998,419.739990,410.720001,415.670013,16935900,0.0,0.0
2025-01-15 00:00:00-05:00,419.130005,428.149994,418.269989,426.309998,19637800,0.0,0.0
2025-01-16 00:00:00-05:00,428.700012,429.489990,424.390015,424.579987,15300000,0.0,0.0
2025-01-17 00:00:00-05:00,434.089996,434.480011,428.170013,429.029999,26197500,0.0,0.0
2025-01-21 00:00:00-05:00,430.200012,430.899994,425.600006,428.500000,26085700,0.0,0.0
2025-01-22 00:00:00-05:00,437.559998,447.269989,436.000000,446.200012,27803800,0.0,0.0
2025-01-23 00:00:00-05:00,442.000000,446.750000,441.500000,446.709991,18389300,0.0,0.0
2025-01-24 00:00:00-05:00,445.160004,446.649994,441.399994,444.059998,15549500,0.0,0.0
2025-01-27 00:00:00-05:00,424.010010,435.200012,423.500000,434.559998,35647800,0.0,0.0
2025-01-28 00:00:00-05:00,434.600006,448.380005,431.380005,447.200012,23491700,0.0,0.0
2025-01-29 00:00:00-05:00,446.690002,446.880005,440.399994,442.329987,23581400,0.0,0.0
2025-01-30 00:00:00-05:00,418.769989,422.859985,413.160004,414.989990,54586300,0.0,0.0
2025-01-31 00:00:00-05:00,418.980011,420.690002,414.910004,415.059998,34223400,0.0,0.0
2025-02-03 00:00:00-05:00,411.600006,415.410004,408.660004,410.920013,25679100,0.0,0.0
2025-02-04 00:00:00-05:00,412.690002,413.920013,409.739990,412.369995,20532100,0.0,0.0
2025-02-05 00:00:00-05:00,412.350006,413.829987,410.399994,413.290009,16316700,0.0,0.0
2025-02-06 00:00:00-05:00,414.000000,418.200012,414.000000,415.820007,16309800,0.0,0.0
2025-02-07 00:00:00-05:00,416.480011,418.649994,408.100006,409.750000,22886800,0.0,0.0
2025-02-10 00:00:00-05:00,413.709991,415.459991,410.920013,412.220001,20817900,0.0,0.0
2025-02-11 00:00:00-05:00,409.640015,412.489990,409.299988,411.440002,18140600,0.0,0.0
2025-02-12 00:00:00-05:00,407.209991,410.750000,404.369995,409.040009,19121700,0.0,0.0
2025-02-13 00:00:00-05:00,407.000000,411.000000,406.359985,410.540009,22907230,0.0,0.0

In [4]:
dat = yf.Ticker("TTWO")
dat.history(period='1mo')
#dat.option_chain(dat.options[0]).calls

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-01-14 00:00:00-05:00,178.910004,181.529999,178.649994,180.029999,876200,0.0,0.0
2025-01-15 00:00:00-05:00,183.399994,183.800003,179.580002,181.320007,1332000,0.0,0.0
2025-01-16 00:00:00-05:00,182.270004,184.460007,181.259995,183.369995,1282200,0.0,0.0
2025-01-17 00:00:00-05:00,186.949997,186.949997,184.820007,186.410004,1443700,0.0,0.0
2025-01-21 00:00:00-05:00,187.550003,189.039993,184.429993,185.139999,1611200,0.0,0.0
2025-01-22 00:00:00-05:00,185.360001,188.179993,183.539993,187.990005,1548500,0.0,0.0
2025-01-23 00:00:00-05:00,183.279999,184.690002,179.610001,183.820007,2066900,0.0,0.0
2025-01-24 00:00:00-05:00,184.000000,185.630005,182.570007,185.490005,1638800,0.0,0.0
2025-01-27 00:00:00-05:00,185.050003,190.580002,184.179993,187.869995,2335500,0.0,0.0
2025-01-28 00:00:00-05:00,186.850006,189.699997,185.729996,187.139999,1616100,0.0,0.0
2025-01-29 00:00:00-05:00,186.919998,191.610001,186.919998,190.089996,1430400,0.0,0.0
2025-01-30 00:00:00-05:00,190.910004,192.500000,189.880005,191.229996,1213100,0.0,0.0
2025-01-31 00:00:00-05:00,190.070007,190.929993,185.389999,185.509995,1680700,0.0,0.0
2025-02-03 00:00:00-05:00,184.619995,187.589996,182.889999,186.070007,1741400,0.0,0.0
2025-02-04 00:00:00-05:00,186.139999,186.610001,182.660004,183.539993,1661200,0.0,0.0
2025-02-05 00:00:00-05:00,185.100006,186.169998,182.919998,184.919998,1697800,0.0,0.0
2025-02-06 00:00:00-05:00,184.080002,184.529999,181.860001,183.080002,2779700,0.0,0.0
2025-02-07 00:00:00-05:00,198.000000,212.880005,195.970001,208.770004,6798600,0.0,0.0
2025-02-10 00:00:00-05:00,210.009995,215.839996,206.279999,212.509995,3454100,0.0,0.0
2025-02-11 00:00:00-05:00,212.270004,214.039993,208.380005,209.940002,1783200,0.0,0.0
2025-02-12 00:00:00-05:00,207.429993,210.110001,206.559998,209.179993,1162800,0.0,0.0
2025-02-13 00:00:00-05:00,209.179993,210.500000,207.824997,210.089996,1332381,0.0,0.0

In [10]:
ticker1 = "MSFT"
industry1 = "Technology"
dat = yf.Ticker(ticker)
df1 = dat.history(period='1mo')

# Reset index to make 'Date' a column
df1 = df1.reset_index()

# Add a new column with the ticker name
df1["Ticker"] = ticker1
df1["Industry"] = industry1
df1 = df1.drop(columns=["Dividends", "Stock Splits"])

# Display the DataFrame
print(df1)

                        Date        Open        High         Low       Close  \
0  2025-01-15 00:00:00-05:00  419.130005  428.149994  418.269989  426.309998
1  2025-01-16 00:00:00-05:00  428.700012  429.489990  424.390015  424.579987
2  2025-01-17 00:00:00-05:00  434.089996  434.480011  428.170013  429.029999
3  2025-01-21 00:00:00-05:00  430.200012  430.899994  425.600006  428.500000
4  2025-01-22 00:00:00-05:00  437.559998  447.269989  436.000000  446.200012
5  2025-01-23 00:00:00-05:00  442.000000  446.750000  441.500000  446.709991
6  2025-01-24 00:00:00-05:00  445.160004  446.649994  441.399994  444.059998
7  2025-01-27 00:00:00-05:00  424.010010  435.200012  423.500000  434.559998
8  2025-01-28 00:00:00-05:00  434.600006  448.380005  431.380005  447.200012
9  2025-01-29 00:00:00-05:00  446.690002  446.880005  440.399994  442.329987
10 2025-01-30 00:00:00-05:00  418.769989  422.859985  413.160004  414.989990
11 2025-01-31 00:00:00-05:00  418.980011  420.690002  414.910004  415.059998
12 2025-02-03 00:00:00-05:00  411.600006  415.410004  408.660004  410.920013
13 2025-02-04 00:00:00-05:00  412.690002  413.920013  409.739990  412.369995
14 2025-02-05 00:00:00-05:00  412.350006  413.829987  410.399994  413.290009
15 2025-02-06 00:00:00-05:00  414.000000  418.200012  414.000000  415.820007
16 2025-02-07 00:00:00-05:00  416.480011  418.649994  408.100006  409.750000
17 2025-02-10 00:00:00-05:00  413.709991  415.459991  410.920013  412.220001
18 2025-02-11 00:00:00-05:00  409.640015  412.489990  409.299988  411.440002
19 2025-02-12 00:00:00-05:00  407.209991  410.750000  404.369995  409.040009
20 2025-02-13 00:00:00-05:00  407.000000  411.000000  406.359985  410.540009
21 2025-02-14 00:00:00-05:00  407.790009  408.910004  405.880005  408.429993

      Volume Ticker    Industry
0   19637800   MSFT  Technology
1   15300000   MSFT  Technology
2   26197500   MSFT  Technology
3   26085700   MSFT  Technology
4   27803800   MSFT  Technology
5   18389300   MSFT  Technology
6   15549500   MSFT  Technology
7   35647800   MSFT  Technology
8   23491700   MSFT  Technology
9   23581400   MSFT  Technology
10  54586300   MSFT  Technology
11  34223400   MSFT  Technology
12  25679100   MSFT  Technology
13  20532100   MSFT  Technology
14  16316700   MSFT  Technology
15  16309800   MSFT  Technology
16  22886800   MSFT  Technology
17  20817900   MSFT  Technology
18  18140600   MSFT  Technology
19  19121700   MSFT  Technology
20  23891700   MSFT  Technology
21  22680000   MSFT  Technology

In [20]:
ticker2 = "TTWO"
dat = yf.Ticker(ticker)
df2 = dat.history(period='1mo')

# Reset index to make 'Date' a column
df2 = df2.reset_index()

# Add a new column with the ticker name
df2["Ticker"] = ticker2

# Display the DataFrame
print(df2)

                        Date        Open        High         Low       Close  \
0  2025-01-14 00:00:00-05:00  417.809998  419.739990  410.720001  415.670013
1  2025-01-15 00:00:00-05:00  419.130005  428.149994  418.269989  426.309998
2  2025-01-16 00:00:00-05:00  428.700012  429.489990  424.390015  424.579987
3  2025-01-17 00:00:00-05:00  434.089996  434.480011  428.170013  429.029999
4  2025-01-21 00:00:00-05:00  430.200012  430.899994  425.600006  428.500000
5  2025-01-22 00:00:00-05:00  437.559998  447.269989  436.000000  446.200012
6  2025-01-23 00:00:00-05:00  442.000000  446.750000  441.500000  446.709991
7  2025-01-24 00:00:00-05:00  445.160004  446.649994  441.399994  444.059998
8  2025-01-27 00:00:00-05:00  424.010010  435.200012  423.500000  434.559998
9  2025-01-28 00:00:00-05:00  434.600006  448.380005  431.380005  447.200012
10 2025-01-29 00:00:00-05:00  446.690002  446.880005  440.399994  442.329987
11 2025-01-30 00:00:00-05:00  418.769989  422.859985  413.160004  414.989990
12 2025-01-31 00:00:00-05:00  418.980011  420.690002  414.910004  415.059998
13 2025-02-03 00:00:00-05:00  411.600006  415.410004  408.660004  410.920013
14 2025-02-04 00:00:00-05:00  412.690002  413.920013  409.739990  412.369995
15 2025-02-05 00:00:00-05:00  412.350006  413.829987  410.399994  413.290009
16 2025-02-06 00:00:00-05:00  414.000000  418.200012  414.000000  415.820007
17 2025-02-07 00:00:00-05:00  416.480011  418.649994  408.100006  409.750000
18 2025-02-10 00:00:00-05:00  413.709991  415.459991  410.920013  412.220001
19 2025-02-11 00:00:00-05:00  409.640015  412.489990  409.299988  411.440002
20 2025-02-12 00:00:00-05:00  407.209991  410.750000  404.369995  409.040009
21 2025-02-13 00:00:00-05:00  407.032013  411.000000  406.359985  410.540009

      Volume  Dividends  Stock Splits Ticker
0   16935900        0.0           0.0   TTWO
1   19637800        0.0           0.0   TTWO
2   15300000        0.0           0.0   TTWO
3   26197500        0.0           0.0   TTWO
4   26085700        0.0           0.0   TTWO
5   27803800        0.0           0.0   TTWO
6   18389300        0.0           0.0   TTWO
7   15549500        0.0           0.0   TTWO
8   35647800        0.0           0.0   TTWO
9   23491700        0.0           0.0   TTWO
10  23581400        0.0           0.0   TTWO
11  54586300        0.0           0.0   TTWO
12  34223400        0.0           0.0   TTWO
13  25679100        0.0           0.0   TTWO
14  20532100        0.0           0.0   TTWO
15  16316700        0.0           0.0   TTWO
16  16309800        0.0           0.0   TTWO
17  22886800        0.0           0.0   TTWO
18  20817900        0.0           0.0   TTWO
19  18140600        0.0           0.0   TTWO
20  19121700        0.0           0.0   TTWO
21  22907230        0.0           0.0   TTWO

In [21]:
pd.concat([df1,df2])

,index,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,Ticker
0,0.0,2025-01-14 00:00:00-05:00,417.809998,419.739990,410.720001,415.670013,16935900,0.0,0.0,MSFT
1,1.0,2025-01-15 00:00:00-05:00,419.130005,428.149994,418.269989,426.309998,19637800,0.0,0.0,MSFT
2,2.0,2025-01-16 00:00:00-05:00,428.700012,429.489990,424.390015,424.579987,15300000,0.0,0.0,MSFT
3,3.0,2025-01-17 00:00:00-05:00,434.089996,434.480011,428.170013,429.029999,26197500,0.0,0.0,MSFT
4,4.0,2025-01-21 00:00:00-05:00,430.200012,430.899994,425.600006,428.500000,26085700,0.0,0.0,MSFT
5,5.0,2025-01-22 00:00:00-05:00,437.559998,447.269989,436.000000,446.200012,27803800,0.0,0.0,MSFT
6,6.0,2025-01-23 00:00:00-05:00,442.000000,446.750000,441.500000,446.709991,18389300,0.0,0.0,MSFT
7,7.0,2025-01-24 00:00:00-05:00,445.160004,446.649994,441.399994,444.059998,15549500,0.0,0.0,MSFT
8,8.0,2025-01-27 00:00:00-05:00,424.010010,435.200012,423.500000,434.559998,35647800,0.0,0.0,MSFT
9,9.0,2025-01-28 00:00:00-05:00,434.600006,448.380005,431.380005,447.200012,23491700,0.0,0.0,MSFT
10,10.0,2025-01-29 00:00:00-05:00,446.690002,446.880005,440.399994,442.329987,23581400,0.0,0.0,MSFT
11,11.0,2025-01-30 00:00:00-05:00,418.769989,422.859985,413.160004,414.989990,54586300,0.0,0.0,MSFT
12,12.0,2025-01-31 00:00:00-05:00,418.980011,420.690002,414.910004,415.059998,34223400,0.0,0.0,MSFT
13,13.0,2025-02-03 00:00:00-05:00,411.600006,415.410004,408.660004,410.920013,25679100,0.0,0.0,MSFT
14,14.0,2025-02-04 00:00:00-05:00,412.690002,413.920013,409.739990,412.369995,20532100,0.0,0.0,MSFT
15,15.0,2025-02-05 00:00:00-05:00,412.350006,413.829987,410.399994,413.290009,16316700,0.0,0.0,MSFT
16,16.0,2025-02-06 00:00:00-05:00,414.000000,418.200012,414.000000,415.820007,16309800,0.0,0.0,MSFT
17,17.0,2025-02-07 00:00:00-05:00,416.480011,418.649994,408.100006,409.750000,22886800,0.0,0.0,MSFT
18,18.0,2025-02-10 00:00:00-05:00,413.709991,415.459991,410.920013,412.220001,20817900,0.0,0.0,MSFT
19,19.0,2025-02-11 00:00:00-05:00,409.640015,412.489990,409.299988,411.440002,18140600,0.0,0.0,MSFT
20,20.0,2025-02-12 00:00:00-05:00,407.209991,410.750000,404.369995,409.040009,19121700,0.0,0.0,MSFT
21,21.0,2025-02-13 00:00:00-05:00,407.000000,411.000000,406.359985,410.540009,22907230,0.0,0.0,MSFT
0,NaN,2025-01-14 00:00:00-05:00,417.809998,419.739990,410.720001,415.670013,16935900,0.0,0.0,TTWO
1,NaN,2025-01-15 00:00:00-05:00,419.130005,428.149994,418.269989,426.309998,19637800,0.0,0.0,TTWO
2,NaN,2025-01-16 00:00:00-05:00,428.700012,429.489990,424.390015,424.579987,15300000,0.0,0.0,TTWO
3,NaN,2025-01-17 00:00:00-05:00,434.089996,434.480011,428.170013,429.029999,26197500,0.0,0.0,TTWO
4,NaN,2025-01-21 00:00:00-05:00,430.200012,430.899994,425.600006,428.500000,26085700,0.0,0.0,TTWO
5,NaN,2025-01-22 00:00:00-05:00,437.559998,447.269989,436.000000,446.200012,27803800,0.0,0.0,TTWO
6,NaN,2025-01-23 00:00:00-05:00,442.000000,446.750000,441.500000,446.709991,18389300,0.0,0.0,TTWO
7,NaN,2025-01-24 00:00:00-05:00,445.160004,446.649994,441.399994,444.059998,15549500,0.0,0.0,TTWO
8,NaN,2025-01-27 00:00:00-05:00,424.010010,435.200012,423.500000,434.559998,35647800,0.0,0.0,TTWO
9,NaN,2025-01-28 00:00:00-05:00,434.600006,448.380005,431.380005,447.200012,23491700,0.0,0.0,TTWO
10,NaN,2025-01-29 00:00:00-05:00,446.690002,446.880005,440.399994,442.329987,23581400,0.0,0.0,TTWO
11,NaN,2025-01-30 00:00:00-05:00,418.769989,422.859985,413.160004,414.989990,54586300,0.0,0.0,TTWO
12,NaN,2025-01-31 00:00:00-05:00,418.980011,420.690002,414.910004,415.059998,34223400,0.0,0.0,TTWO
13,NaN,2025-02-03 00:00:00-05:00,411.600006,415.410004,408.660004,410.920013,25679100,0.0,0.0,TTWO
14,NaN,2025-02-04 00:00:00-05:00,412.690002,413.920013,409.739990,412.369995,20532100,0.0,0.0,TTWO
15,NaN,2025-02-05 00:00:00-05:00,412.350006,413.829987,410.399994,413.290009,16316700,0.0,0.0,TTWO
16,NaN,2025-02-06 00:00:00-05:00,414.000000,418.200012,414.000000,415.820007,16309800,0.0,0.0,TTWO
17,NaN,2025-02-07 00:00:00-05:00,416.480011,418.649994,408.100006,409.750000,22886800,0.0,0.0,TTWO
18,NaN,2025-02-10 00:00:00-05:00,413.709991,415.459991,410.920013,412.220001,20817900,0.0,0.0,TTWO
19,NaN,2025-02-11 00:00:00-05:00,409.640015,412.489990,409.299988,411.440002,18140600,0.0,0.0,TTWO
20,NaN,2025-02-12 00:00:00-05:00,407.209991,410.750000,404.369995,409.040009,19121700,0.0,0.0,TTWO
21,NaN,2025-02-13 00:00:00-05:00,407.032013,411.000000,406.359985,410.540009,22907230,0.0,0.0,TTWO

In [11]:
import yfinance as yf

# List of tickers and industry
tickers = ["AAPL", "NVDA", "GOOGL", "AMZN", "META"]
industry = "Technology"

# Loop through each ticker
for ticker in tickers:
    dat = yf.Ticker(ticker)
    df1 = dat.history(period='1mo')

    # Reset index to make 'Date' a column
    df1 = df1.reset_index()

    # Add a new column with the ticker name
    df1["Ticker"] = ticker
    df1["Industry"] = industry

    # Remove unnecessary columns
    df1 = df1.drop(columns=["Dividends", "Stock Splits"])

    # Display the DataFrame
    print(df1)

                        Date        Open        High         Low       Close  \
0  2025-01-15 00:00:00-05:00  234.382301  238.697564  234.172525  237.608749
1  2025-01-16 00:00:00-05:00  237.089336  237.748600  227.779565  228.009308
2  2025-01-17 00:00:00-05:00  231.865066  232.034878  228.229064  229.727417
3  2025-01-21 00:00:00-05:00  223.753984  224.173521  219.139063  222.395477
4  2025-01-22 00:00:00-05:00  219.548596  223.873842  219.548596  223.584167
5  2025-01-23 00:00:00-05:00  224.493183  226.780662  222.055861  223.414368
6  2025-01-24 00:00:00-05:00  224.533128  225.382200  221.166834  222.535324
7  2025-01-27 00:00:00-05:00  223.773962  231.895022  223.733997  229.607544
8  2025-01-28 00:00:00-05:00  230.596471  239.926210  230.556507  237.998322
9  2025-01-29 00:00:00-05:00  233.862872  239.596573  233.752992  239.097122
10 2025-01-30 00:00:00-05:00  238.407871  240.525538  236.949483  237.329056
11 2025-01-31 00:00:00-05:00  246.918527  246.918527  233.183628  235.740814
12 2025-02-03 00:00:00-05:00  229.737419  231.575395  225.452122  227.759583
13 2025-02-04 00:00:00-05:00  227.000419  232.873966  226.401072  232.544327
14 2025-02-05 00:00:00-05:00  228.279016  232.414468  228.019307  232.214691
15 2025-02-06 00:00:00-05:00  231.035979  233.543232  230.176923  232.963867
16 2025-02-07 00:00:00-05:00  232.344548  233.743004  227.010401  227.380005
17 2025-02-10 00:00:00-05:00  229.570007  230.589996  227.199997  227.649994
18 2025-02-11 00:00:00-05:00  228.199997  235.229996  228.130005  232.619995
19 2025-02-12 00:00:00-05:00  231.199997  236.960007  230.679993  236.869995
20 2025-02-13 00:00:00-05:00  236.910004  242.339996  235.570007  241.529999
21 2025-02-14 00:00:00-05:00  241.250000  245.550003  240.990005  244.600006

       Volume Ticker    Industry
0    39832000   AAPL  Technology
1    71759100   AAPL  Technology
2    68488300   AAPL  Technology
3    98070400   AAPL  Technology
4    64126500   AAPL  Technology
5    60234800   AAPL  Technology
6    54697900   AAPL  Technology
7    94863400   AAPL  Technology
8    75707600   AAPL  Technology
9    45486100   AAPL  Technology
10   55658300   AAPL  Technology
11  101075100   AAPL  Technology
12   73063300   AAPL  Technology
13   45067300   AAPL  Technology
14   39620300   AAPL  Technology
15   29925300   AAPL  Technology
16   39707200   AAPL  Technology
17   33115600   AAPL  Technology
18   53718400   AAPL  Technology
19   45243300   AAPL  Technology
20   53614100   AAPL  Technology
21   40838100   AAPL  Technology
                        Date        Open        High         Low       Close  \
0  2025-01-15 00:00:00-05:00  133.649994  136.449997  131.289993  136.240005
1  2025-01-16 00:00:00-05:00  138.639999  138.750000  133.490005  133.570007
2  2025-01-17 00:00:00-05:00  136.690002  138.500000  135.460007  137.710007
3  2025-01-21 00:00:00-05:00  139.160004  141.830002  137.089996  140.830002
4  2025-01-22 00:00:00-05:00  144.660004  147.789993  143.669998  147.070007
5  2025-01-23 00:00:00-05:00  145.050003  147.229996  143.720001  147.220001
6  2025-01-24 00:00:00-05:00  148.369995  148.970001  141.880005  142.619995
7  2025-01-27 00:00:00-05:00  124.800003  128.399994  116.699997  118.419998
8  2025-01-28 00:00:00-05:00  121.809998  129.000000  116.250000  128.990005
9  2025-01-29 00:00:00-05:00  126.500000  126.889999  120.050003  123.699997
10 2025-01-30 00:00:00-05:00  123.099998  125.000000  118.099998  124.650002
11 2025-01-31 00:00:00-05:00  123.779999  127.849998  119.190002  120.070000
12 2025-02-03 00:00:00-05:00  114.750000  118.570000  113.010002  116.660004
13 2025-02-04 00:00:00-05:00  116.959999  121.199997  116.699997  118.650002
14 2025-02-05 00:00:00-05:00  121.760002  125.000000  120.760002  124.830002
15 2025-02-06 00:00:00-05:00  127.419998  128.770004  125.209999  128.679993
16 2025-02-07 00:00:00-05:00  129.220001  130.369995  125.000000  129.839996
17 2025-02-10 00:00:00-05:00  130.089996  135.000000  129.960007  133.570007
18 2025-02-11 00:00:00-05:00  132.580002  134.479996  131.020004  132.800003
19 2025-02-12 00:00:00-05:00  130.020004  132.240005  129.080002  131.139999
20 2025-02-13 00:00:00-05:00  131.559998  136.500000  131.169998  135.289993
21 2025-02-14 00:00:00-05:00  136.479996  139.250000  135.500000  138.850006

       Volume Ticker    Industry
0   185217300   NVDA  Technology
1   209235600   NVDA  Technology
2   201188800   NVDA  Technology
3   197749000   NVDA  Technology
4   237651400   NVDA  Technology
5   155915500   NVDA  Technology
6   234657600   NVDA  Technology
7   818830900   NVDA  Technology
8   579666400   NVDA  Technology
9   467120600   NVDA  Technology
10  392925500   NVDA  Technology
11  390372900   NVDA  Technology
12  371235700   NVDA  Technology
13  256550000   NVDA  Technology
14  262230800   NVDA  Technology
15  251483600   NVDA  Technology
16  228186300   NVDA  Technology
17  216989100   NVDA  Technology
18  178902400   NVDA  Technology
19  160278600   NVDA  Technology
20  197430000   NVDA  Technology
21  194892300   NVDA  Technology
                        Date        Open        High         Low       Close  \
0  2025-01-15 00:00:00-05:00  193.089996  196.360001  191.860001  195.550003
1  2025-01-16 00:00:00-05:00  194.139999  195.479996  192.809998  192.910004
2  2025-01-17 00:00:00-05:00  196.529999  197.229996  193.750000  196.000000
3  2025-01-21 00:00:00-05:00  199.070007  202.289993  197.869995  198.050003
4  2025-01-22 00:00:00-05:00  199.059998  200.479996  197.529999  198.369995
5  2025-01-23 00:00:00-05:00  198.139999  200.300003  195.199997  197.979996
6  2025-01-24 00:00:00-05:00  198.100006  200.899994  198.000000  200.210007
7  2025-01-27 00:00:00-05:00  192.410004  196.880005  190.729996  191.809998
8  2025-01-28 00:00:00-05:00  192.750000  195.479996  190.679993  195.300003
9  2025-01-29 00:00:00-05:00  195.559998  196.789993  193.429993  195.410004
10 2025-01-30 00:00:00-05:00  198.000000  201.399994  197.669998  200.869995
11 2025-01-31 00:00:00-05:00  202.000000  205.479996  201.800003  204.020004
12 2025-02-03 00:00:00-05:00  200.690002  203.750000  200.100006  201.229996
13 2025-02-04 00:00:00-05:00  203.389999  207.050003  202.809998  206.380005
14 2025-02-05 00:00:00-05:00  191.070007  192.750000  188.029999  191.330002
15 2025-02-06 00:00:00-05:00  189.500000  192.100006  188.720001  191.600006
16 2025-02-07 00:00:00-05:00  191.050003  191.179993  183.240005  185.339996
17 2025-02-10 00:00:00-05:00  187.350006  188.199997  185.860001  186.470001
18 2025-02-11 00:00:00-05:00  185.029999  186.940002  184.279999  185.320007
19 2025-02-12 00:00:00-05:00  183.220001  185.110001  181.830002  183.610001
20 2025-02-13 00:00:00-05:00  184.320007  186.279999  183.139999  186.139999
21 2025-02-14 00:00:00-05:00  185.059998  186.399994  184.320007  185.229996

      Volume Ticker    Industry
0   21776000  GOOGL  Technology
1   17815400  GOOGL  Technology
2   27735100  GOOGL  Technology
3   29971300  GOOGL  Technology
4   26200600  GOOGL  Technology
5   26951400  GOOGL  Technology
6   23877500  GOOGL  Technology
7   41728900  GOOGL  Technology
8   24157900  GOOGL  Technology
9   18218300  GOOGL  Technology
10  24354700  GOOGL  Technology
11  32042000  GOOGL  Technology
12  27838300  GOOGL  Technology
13  43856400  GOOGL  Technology
14  70373900  GOOGL  Technology
15  29297400  GOOGL  Technology
16  49315000  GOOGL  Technology
17  23105600  GOOGL  Technology
18  21239500  GOOGL  Technology
19  22072600  GOOGL  Technology
20  21402500  GOOGL  Technology
21  20402300  GOOGL  Technology
                        Date        Open        High         Low       Close  \
0  2025-01-15 00:00:00-05:00  222.830002  223.570007  220.750000  223.350006
1  2025-01-16 00:00:00-05:00  224.419998  224.649994  220.309998  220.660004
2  2025-01-17 00:00:00-05:00  225.839996  226.509995  223.080002  225.940002
3  2025-01-21 00:00:00-05:00  228.899994  231.779999  226.940002  230.710007
4  2025-01-22 00:00:00-05:00  232.020004  235.440002  231.190002  235.009995
5  2025-01-23 00:00:00-05:00  234.100006  235.520004  231.509995  235.419998
6  2025-01-24 00:00:00-05:00  234.500000  236.399994  232.929993  234.850006
7  2025-01-27 00:00:00-05:00  226.210007  235.610001  225.860001  235.419998
8  2025-01-28 00:00:00-05:00  234.289993  241.770004  233.979996  238.149994
9  2025-01-29 00:00:00-05:00  239.020004  240.389999  236.149994  237.070007
10 2025-01-30 00:00:00-05:00  237.139999  237.949997  232.220001  234.639999
11 2025-01-31 00:00:00-05:00  236.500000  240.289993  236.410004  237.679993
12 2025-02-03 00:00:00-05:00  234.059998  239.250000  232.899994  237.419998
13 2025-02-04 00:00:00-05:00  239.009995  242.520004  238.029999  242.059998
14 2025-02-05 00:00:00-05:00  237.020004  238.320007  235.199997  236.169998
15 2025-02-06 00:00:00-05:00  238.009995  239.660004  236.009995  238.830002
16 2025-02-07 00:00:00-05:00  232.500000  234.809998  228.059998  229.149994
17 2025-02-10 00:00:00-05:00  230.550003  233.919998  229.199997  233.139999
18 2025-02-11 00:00:00-05:00  231.919998  233.440002  230.130005  232.759995
19 2025-02-12 00:00:00-05:00  230.460007  231.179993  228.160004  228.929993
20 2025-02-13 00:00:00-05:00  228.850006  230.419998  227.520004  230.369995
21 2025-02-14 00:00:00-05:00  229.199997  229.889999  227.229996  228.679993

      Volume Ticker    Industry
0   31291300   AMZN  Technology
1   24757300   AMZN  Technology
2   42370100   AMZN  Technology
3   39951500   AMZN  Technology
4   41448200   AMZN  Technology
5   26404400   AMZN  Technology
6   25890700   AMZN  Technology
7   49428300   AMZN  Technology
8   41587200   AMZN  Technology
9   26091700   AMZN  Technology
10  32020700   AMZN  Technology
11  36162400   AMZN  Technology
12  37285900   AMZN  Technology
13  29713800   AMZN  Technology
14  38727300   AMZN  Technology
15  60897100   AMZN  Technology
16  77539300   AMZN  Technology
17  35419900   AMZN  Technology
18  23713700   AMZN  Technology
19  32285200   AMZN  Technology
20  31346500   AMZN  Technology
21  26973200   AMZN  Technology
                        Date        Open        High         Low       Close  \
0  2025-01-15 00:00:00-05:00  610.210022  622.460022  606.500000  617.119995
1  2025-01-16 00:00:00-05:00  611.500000  616.250000  609.710022  611.299988
2  2025-01-17 00:00:00-05:00  624.049988  624.969971  603.669983  612.770020
3  2025-01-21 00:00:00-05:00  617.830017  621.500000  609.010010  616.460022
4  2025-01-22 00:00:00-05:00  623.299988  633.700012  619.429993  623.500000
5  2025-01-23 00:00:00-05:00  627.359985  636.599976  621.150024  636.450012
6  2025-01-24 00:00:00-05:00  636.400024  652.000000  634.200012  647.489990
7  2025-01-27 00:00:00-05:00  626.609985  663.869995  625.099976  659.880005
8  2025-01-28 00:00:00-05:00  666.000000  682.580017  659.469971  674.330017
9  2025-01-29 00:00:00-05:00  675.000000  681.049988  665.669983  676.489990
10 2025-01-30 00:00:00-05:00  696.820007  710.789978  676.099976  687.000000
11 2025-01-31 00:00:00-05:00  691.000000  705.299988  685.580017  689.179993
12 2025-02-03 00:00:00-05:00  675.909973  704.000000  675.250000  697.460022
13 2025-02-04 00:00:00-05:00  702.500000  707.710022  691.609985  704.190002
14 2025-02-05 00:00:00-05:00  703.549988  718.140015  699.010010  704.869995
15 2025-02-06 00:00:00-05:00  705.880005  718.900024  703.500000  711.989990
16 2025-02-07 00:00:00-05:00  716.799988  725.010010  711.750000  714.520020
17 2025-02-10 00:00:00-05:00  718.559998  721.200012  711.330017  717.400024
18 2025-02-11 00:00:00-05:00  713.320007  723.659973  710.039978  719.799988
19 2025-02-12 00:00:00-05:00  715.299988  727.099976  712.599976  725.380005
20 2025-02-13 00:00:00-05:00  721.520020  729.000000  718.039978  728.559998
21 2025-02-14 00:00:00-05:00  726.140015  740.909973  725.619995  736.669983

      Volume Ticker    Industry
0   15524300   META  Technology
1    8355300   META  Technology
2   17280600   META  Technology
3   11674000   META  Technology
4   12274000   META  Technology
5    9910200   META  Technology
6   19065300   META  Technology
7   28399200   META  Technology
8   20950100   META  Technology
9   21377800   META  Technology
10  29322900   META  Technology
11  19331700   META  Technology
12  21415700   META  Technology
13  13826300   META  Technology
14  17778200   META  Technology
15  13080700   META  Technology
16  16427100   META  Technology
17  12904300   META  Technology
18  12998000   META  Technology
19  12016500   META  Technology
20  12569100   META  Technology
21  16884300   META  Technology

In [2]:
# Microsoft (MSFT) - Original Example
ticker1 = "MSFT"
industry1 = "Technology"
dat = yf.Ticker(ticker1)
df1 = dat.history(period='1mo')
df1 = df1.reset_index()
df1["Ticker"] = ticker1
df1["Industry"] = industry1
df1 = df1.drop(columns=["Dividends", "Stock Splits"])

# Apple (AAPL)
ticker2 = "AAPL"
industry2 = "Technology"
dat = yf.Ticker(ticker2)
df2 = dat.history(period='1mo')
df2 = df2.reset_index()
df2["Ticker"] = ticker2
df2["Industry"] = industry2
df2 = df2.drop(columns=["Dividends", "Stock Splits"])

# Nvidia (NVDA)
ticker3 = "NVDA"
industry3 = "Technology"
dat = yf.Ticker(ticker3)
df3 = dat.history(period='1mo')
df3 = df3.reset_index()
df3["Ticker"] = ticker3
df3["Industry"] = industry3
df3 = df3.drop(columns=["Dividends", "Stock Splits"])

# Google (GOOGL)
ticker4 = "GOOGL"
industry4 = "Technology"
dat = yf.Ticker(ticker4)
df4 = dat.history(period='1mo')
df4 = df4.reset_index()
df4["Ticker"] = ticker4
df4["Industry"] = industry4
df4 = df4.drop(columns=["Dividends", "Stock Splits"])

# Amazon (AMZN)
ticker5 = "AMZN"
industry5 = "Technology"
dat = yf.Ticker(ticker5)
df5 = dat.history(period='1mo')
df5 = df5.reset_index()
df5["Ticker"] = ticker5
df5["Industry"] = industry5
df5 = df5.drop(columns=["Dividends", "Stock Splits"])

# Meta (META)
ticker6 = "META"
industry6 = "Technology"
dat = yf.Ticker(ticker6)
df6 = dat.history(period='1mo')
df6 = df6.reset_index()
df6["Ticker"] = ticker6
df6["Industry"] = industry6
df6 = df6.drop(columns=["Dividends", "Stock Splits"])

# Concatenate all DataFrames
final_df = pd.concat([df1, df2, df3, df4, df5, df6], ignore_index=True)

# Display the final DataFrame
print(final_df)

YFRateLimitError: Too Many Requests. Rate limited. Try after a while.

In [1]:
import yfinance as yf
import pandas as pd

# Microsoft (MSFT) - Original Example
ticker1 = "MSFT"
industry1 = "Technology"
dat = yf.Ticker(ticker1)
df1 = dat.history(period='1mo')
df1 = df1.reset_index()
df1["Ticker"] = ticker1
df1["Industry"] = industry1
df1 = df1.drop(columns=["Dividends", "Stock Splits"])

# Apple (AAPL)
ticker2 = "AAPL"
industry2 = "Technology"
dat = yf.Ticker(ticker2)
df2 = dat.history(period='1mo')
df2 = df2.reset_index()
df2["Ticker"] = ticker2
df2["Industry"] = industry2
df2 = df2.drop(columns=["Dividends", "Stock Splits"])

# Nvidia (NVDA)
ticker3 = "NVDA"
industry3 = "Technology"
dat = yf.Ticker(ticker3)
df3 = dat.history(period='1mo')
df3 = df3.reset_index()
df3["Ticker"] = ticker3
df3["Industry"] = industry3
df3 = df3.drop(columns=["Dividends", "Stock Splits"])

# Google (GOOGL)
ticker4 = "GOOGL"
industry4 = "Technology"
dat = yf.Ticker(ticker4)
df4 = dat.history(period='1mo')
df4 = df4.reset_index()
df4["Ticker"] = ticker4
df4["Industry"] = industry4
df4 = df4.drop(columns=["Dividends", "Stock Splits"])

# Amazon (AMZN)
ticker5 = "AMZN"
industry5 = "Technology"
dat = yf.Ticker(ticker5)
df5 = dat.history(period='1mo')
df5 = df5.reset_index()
df5["Ticker"] = ticker5
df5["Industry"] = industry5
df5 = df5.drop(columns=["Dividends", "Stock Splits"])

# Meta (META)
ticker6 = "META"
industry6 = "Technology"
dat = yf.Ticker(ticker6)
df6 = dat.history(period='1mo')
df6 = df6.reset_index()
df6["Ticker"] = ticker6
df6["Industry"] = industry6
df6 = df6.drop(columns=["Dividends", "Stock Splits"])

# Healthcare - Johnson & Johnson (JNJ)
ticker7 = "JNJ"
industry7 = "Healthcare"
dat = yf.Ticker(ticker7)
df7 = dat.history(period='1mo')
df7 = df7.reset_index()
df7["Ticker"] = ticker7
df7["Industry"] = industry7
df7 = df7.drop(columns=["Dividends", "Stock Splits"])

# Healthcare - Pfizer (PFE)
ticker8 = "PFE"
industry8 = "Healthcare"
dat = yf.Ticker(ticker8)
df8 = dat.history(period='1mo')
df8 = df8.reset_index()
df8["Ticker"] = ticker8
df8["Industry"] = industry8
df8 = df8.drop(columns=["Dividends", "Stock Splits"])

# Healthcare - Moderna (MRNA)
ticker9 = "MRNA"
industry9 = "Healthcare"
dat = yf.Ticker(ticker9)
df9 = dat.history(period='1mo')
df9 = df9.reset_index()
df9["Ticker"] = ticker9
df9["Industry"] = industry9
df9 = df9.drop(columns=["Dividends", "Stock Splits"])

# Healthcare - UnitedHealth Group (UNH)
ticker10 = "UNH"
industry10 = "Healthcare"
dat = yf.Ticker(ticker10)
df10 = dat.history(period='1mo')
df10 = df10.reset_index()
df10["Ticker"] = ticker10
df10["Industry"] = industry10
df10 = df10.drop(columns=["Dividends", "Stock Splits"])

# Healthcare - Eli Lilly (LLY)
ticker11 = "LLY"
industry11 = "Healthcare"
dat = yf.Ticker(ticker11)
df11 = dat.history(period='1mo')
df11 = df11.reset_index()
df11["Ticker"] = ticker11
df11["Industry"] = industry11
df11 = df11.drop(columns=["Dividends", "Stock Splits"])

# Healthcare - Merck & Co. (MRK)
ticker12 = "MRK"
industry12 = "Healthcare"
dat = yf.Ticker(ticker12)
df12 = dat.history(period='1mo')
df12 = df12.reset_index()
df12["Ticker"] = ticker12
df12["Industry"] = industry12
df12 = df12.drop(columns=["Dividends", "Stock Splits"])

# Healthcare - Merck & Co. (MRK)
ticker12 = "MRK"
industry12 = "Healthcare"
dat12 = yf.Ticker(ticker12)
df12 = dat12.history(period='1mo')
df12 = df12.reset_index()
df12["Ticker"] = ticker12
df12["Industry"] = industry12
df12 = df12.drop(columns=["Dividends", "Stock Splits"])

# Energy - ExxonMobil (XOM)
ticker13 = "XOM"
industry13 = "Energy"
dat13 = yf.Ticker(ticker13)
df13 = dat13.history(period='1mo')
df13 = df13.reset_index()
df13["Ticker"] = ticker13
df13["Industry"] = industry13
df13 = df13.drop(columns=["Dividends", "Stock Splits"])

# Energy - Chevron (CVX)
ticker14 = "CVX"
industry14 = "Energy"
dat14 = yf.Ticker(ticker14)
df14 = dat14.history(period='1mo')
df14 = df14.reset_index()
df14["Ticker"] = ticker14
df14["Industry"] = industry14
df14 = df14.drop(columns=["Dividends", "Stock Splits"])

# Energy - Shell (SHEL)
ticker15 = "SHEL"
industry15 = "Energy"
dat15 = yf.Ticker(ticker15)
df15 = dat15.history(period='1mo')
df15 = df15.reset_index()
df15["Ticker"] = ticker15
df15["Industry"] = industry15
df15 = df15.drop(columns=["Dividends", "Stock Splits"])

# Energy - BP (BP)
ticker16 = "BP"
industry16 = "Energy"
dat16 = yf.Ticker(ticker16)
df16 = dat16.history(period='1mo')
df16 = df16.reset_index()
df16["Ticker"] = ticker16
df16["Industry"] = industry16
df16 = df16.drop(columns=["Dividends", "Stock Splits"])

# Energy - TotalEnergies (TTE)
ticker17 = "TTE"
industry17 = "Energy"
dat17 = yf.Ticker(ticker17)
df17 = dat17.history(period='1mo')
df17 = df17.reset_index()
df17["Ticker"] = ticker17
df17["Industry"] = industry17
df17 = df17.drop(columns=["Dividends", "Stock Splits"])

# Energy - NextEra Energy (NEE)
ticker18 = "NEE"
industry18 = "Energy"
dat18 = yf.Ticker(ticker18)
df18 = dat18.history(period='1mo')
df18 = df18.reset_index()
df18["Ticker"] = ticker18
df18["Industry"] = industry18
df18 = df18.drop(columns=["Dividends", "Stock Splits"])

# Communication - Verizon (VZ)
ticker19 = "VZ"
industry19 = "Communication"
dat19 = yf.Ticker(ticker19)
df19 = dat19.history(period='1mo')
df19 = df19.reset_index()
df19["Ticker"] = ticker19
df19["Industry"] = industry19
df19 = df19.drop(columns=["Dividends", "Stock Splits"])

# Communication - AT&T (T)
ticker20 = "T"
industry20 = "Communication"
dat20 = yf.Ticker(ticker20)
df20 = dat20.history(period='1mo')
df20 = df20.reset_index()
df20["Ticker"] = ticker20
df20["Industry"] = industry20
df20 = df20.drop(columns=["Dividends", "Stock Splits"])

# Communication - Vodafone (VOD)
ticker22 = "VOD"
industry22 = "Communication"
dat22 = yf.Ticker(ticker22)
df22 = dat22.history(period='1mo')
df22 = df22.reset_index()
df22["Ticker"] = ticker22
df22["Industry"] = industry22
df22 = df22.drop(columns=["Dividends", "Stock Splits"])

# Communication - Deutsche Telekom (DTEGY)
ticker23 = "DTEGY"
industry23 = "Communication"
dat23 = yf.Ticker(ticker23)
df23 = dat23.history(period='1mo')
df23 = df23.reset_index()
df23["Ticker"] = ticker23
df23["Industry"] = industry23
df23 = df23.drop(columns=["Dividends", "Stock Splits"])

# Communication - T-Mobile US (TMUS)
ticker24 = "TMUS"
industry24 = "Communication"
dat24 = yf.Ticker(ticker24)
df24 = dat24.history(period='1mo')
df24 = df24.reset_index()
df24["Ticker"] = ticker24
df24["Industry"] = industry24
df24 = df24.drop(columns=["Dividends", "Stock Splits"])

# Concatenate all DataFrames
final_df = pd.concat([df12, df13, df14, df15, df16, df17, df18, df19, df20, df22, df23, df24])

# Display the final DataFrame
print(final_df)

YFRateLimitError: Too Many Requests. Rate limited. Try after a while.

In [19]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\anaconda3\lib\site-packages (3.1.2)
Requirement already satisfied: et-xmlfile in c:\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
final_df.to_excel("final_stocks_data.xlsx", engine='openpyxl')

print("Data exported to final_stocks_data.xlsx")

NameError: name 'final_df' is not defined